import {
  IoMdSend,
  IoIosArrowDropleftCircle,
  IoIosArrowDroprightCircle,
  IoMdHeartEmpty,
  IoMdHeart,
} from "react-icons/io";
import { PiBellRingingFill, PiChartDonutFill } from "react-icons/pi";
import { FcGoogle } from "react-icons/fc";
import { FiSearch, FiChevronDown, FiEdit } from "react-icons/fi";
import {
  IoAlbumsSharp,
  IoLogOutOutline,
  IoKeyOutline,
  IoBriefcaseOutline,
  IoBookmark,
  IoBriefcase,
  IoAddCircle,
  IoSendSharp,
  IoSettingsSharp,
  IoArrowRedoCircleOutline,
  IoArrowUndoCircleOutline,
  IoCloseCircleSharp,
  IoAlertSharp,
  IoRemove,
  IoClose,
} from "react-icons/io5";
import {
  MdFontDownload,
  MdEmail,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdImagesearchRoller,
  MdPayment,
} from "react-icons/md";
import {
  BsFillImageFill,
  BsCheckCircleFill,
  BsMessenger,
  BsCalendar3,
  BsBarChartLineFill,
  BsCameraFill,
  BsCameraVideo,
  BsTelephone,
  BsFillCheckCircleFill,
  BsArrowsFullscreen,
} from "react-icons/bs";
import { FaUserAlt, FaUserCircle, FaSignOutAlt } from "react-icons/fa";
import { BiSolidPhoneCall } from "react-icons/bi";
import { HiLocationMarker } from "react-icons/hi";
import {
  FaCircleChevronUp,
  FaCircleChevronDown,
  FaCirclePlus,
  FaCircleXmark,
  FaFaceSmile,
  FaUserCheck,
} from "react-icons/fa6";
import {
  AiOutlineBold,
  AiOutlineUnderline,
  AiOutlineItalic,
  AiFillDollarCircle,
  AiFillClockCircle,
  AiFillCloseCircle,
  AiOutlineComment,
} from "react-icons/ai";
import { HiOutlineVideoCamera, HiHome, HiDocumentText } from "react-icons/hi2";

const icons = {
  IoMdHeartEmpty,
  IoMdHeart,
  AiOutlineComment,
  IoClose,
  IoRemove,
  BsArrowsFullscreen,
  PiChartDonutFill,
  IoCloseCircleSharp,
  BsFillCheckCircleFill,
  IoIosArrowDropleftCircle,
  IoIosArrowDroprightCircle,
  IoAlertSharp,
  BsTelephone,
  BsCameraVideo,
  FaUserCheck,
  MdPayment,
  FaSignOutAlt,
  MdImagesearchRoller,
  AiFillCloseCircle,
  AiFillClockCircle,
  AiFillDollarCircle,
  HiLocationMarker,
  IoArrowUndoCircleOutline,
  IoArrowRedoCircleOutline,
  BsCameraFill,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  IoSettingsSharp,
  BsBarChartLineFill,
  HiDocumentText,
  HiHome,
  FaFaceSmile,
  IoSendSharp,
  FaUserCircle,
  BiSolidPhoneCall,
  MdEmail,
  IoBriefcase,
  IoAddCircle,
  BsCheckCircleFill,
  HiOutlineVideoCamera,
  PiBellRingingFill,
  BsCalendar3,
  BsMessenger,
  IoBookmark,
  FiEdit,
  IoLogOutOutline,
  IoKeyOutline,
  IoMdSend,
  IoBriefcaseOutline,
  BsFillImageFill,
  FaUserAlt,
  MdFontDownload,
  IoAlbumsSharp,
  AiOutlineBold,
  AiOutlineUnderline,
  AiOutlineItalic,
  FaCircleChevronUp,
  FaCircleChevronDown,
  FaCirclePlus,
  FaCircleXmark,
  FiSearch,
  FcGoogle,
  FiChevronDown,
};

export { icons };
