import {
  IoMdSend,
  IoIosArrowDroprightCircle,
  IoIosArrowDropleftCircle,
  IoMdEyeOff,
  IoMdHeartEmpty,
  IoMdHeart,
} from "react-icons/io";
import { PiBellRingingFill, PiChartDonutFill } from "react-icons/pi";
import { FcGoogle } from "react-icons/fc";
import { FiSearch, FiChevronDown, FiEdit } from "react-icons/fi";
import {
  IoAlbumsSharp,
  IoLogOutOutline,
  IoKeyOutline,
  IoBriefcaseOutline,
  IoBookmark,
  IoBriefcase,
  IoAddCircle,
  IoSendSharp,
  IoSettingsSharp,
  IoArrowRedoCircleOutline,
  IoArrowUndoCircleOutline,
  IoLocationSharp,
  IoCloseCircleSharp,
  IoBookmarkOutline,
  IoAlertSharp,
  IoRemove,
  IoEye,
  IoClose,
  IoMicSharp,
  IoAttach,
  IoLinkOutline,
  IoChatbubbleEllipsesOutline,
} from "react-icons/io5";
import {
  MdFontDownload,
  MdEmail,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  MdPhoneInTalk,
  MdColorLens,
  MdAccessTimeFilled,
  MdDeleteForever,
} from "react-icons/md";
import {
  BsFillImageFill,
  BsCheckCircleFill,
  BsMessenger,
  BsCalendar3,
  BsBarChartLineFill,
  BsCameraFill,
  BsFacebook,
  BsFileEarmarkArrowDownFill,
  BsFiletypePdf,
  BsCameraVideo,
  BsTelephone,
  BsFillCheckCircleFill,
  BsArrowsFullscreen,
  BsFileTextFill,
} from "react-icons/bs";
import {
  FaUserAlt,
  FaUserCircle,
  FaGripVertical,
  FaBars,
  FaUserFriends,
  FaHeadphonesAlt,
  FaBriefcase,
  FaListUl,
} from "react-icons/fa";
import {
  BiSolidPhoneCall,
  BiLoaderCircle,
  BiSolidBuildingHouse,
} from "react-icons/bi";
import { HiLocationMarker } from "react-icons/hi";
import {
  FaCircleChevronUp,
  FaCircleChevronDown,
  FaCirclePlus,
  FaCircleXmark,
  FaFaceSmile,
  FaStar,
  FaCircleInfo,
  FaLock,
  FaDollarSign,
  FaFont,
  FaUserCheck,
  FaUserPlus,
  FaDeleteLeft,
} from "react-icons/fa6";
import {
  AiOutlineBold,
  AiOutlineUnderline,
  AiOutlineItalic,
  AiFillDollarCircle,
  AiFillClockCircle,
  AiFillCloseCircle,
  AiOutlineComment,
} from "react-icons/ai";

import { HiOutlineVideoCamera, HiHome, HiDocumentText } from "react-icons/hi2";
import { HiFilter, HiDotsVertical } from "react-icons/hi";
import { GrReactjs, GrNode } from "react-icons/gr";
import { SiTailwindcss, SiExpress } from "react-icons/si";
import { DiMongodb } from "react-icons/di";
import { LiaSearchPlusSolid, LiaSearchMinusSolid } from "react-icons/lia";
import { ImTable2 } from "react-icons/im";
import { TbExternalLink } from "react-icons/tb";

const icons = {
  MdDeleteForever,
  IoChatbubbleEllipsesOutline,
  IoMdHeartEmpty,
  IoMdHeart,
  AiOutlineComment,
  IoLinkOutline,
  IoMicSharp,
  IoAttach,
  HiDotsVertical,
  IoEye,
  IoMdEyeOff,
  BsFileTextFill,
  FaListUl,
  TbExternalLink,
  MdAccessTimeFilled,
  FaDeleteLeft,
  BsArrowsFullscreen,
  IoRemove,
  IoClose,
  IoAlertSharp,
  BsFillCheckCircleFill,
  PiChartDonutFill,
  IoMdSend,
  IoBookmarkOutline,
  FaUserPlus,
  BsTelephone,
  BsCameraVideo,
  FaUserCheck,
  ImTable2,
  AiFillCloseCircle,
  BsFiletypePdf,
  FaFont,
  MdColorLens,
  BsFileEarmarkArrowDownFill,
  LiaSearchPlusSolid,
  LiaSearchMinusSolid,
  BsFacebook,
  FaHeadphonesAlt,
  FaDollarSign,
  FaLock,
  FaBriefcase,
  IoCloseCircleSharp,
  IoIosArrowDroprightCircle,
  IoIosArrowDropleftCircle,
  FaCircleInfo,
  FaUserFriends,
  IoLocationSharp,
  MdPhoneInTalk,
  BiSolidBuildingHouse,
  SiTailwindcss,
  SiExpress,
  DiMongodb,
  FaBars,
  GrReactjs,
  GrNode,
  FaGripVertical,
  BiLoaderCircle,
  FaStar,
  HiFilter,
  AiFillClockCircle,
  AiFillDollarCircle,
  HiLocationMarker,
  IoArrowUndoCircleOutline,
  IoArrowRedoCircleOutline,
  BsCameraFill,
  MdKeyboardArrowRight,
  MdKeyboardArrowUp,
  IoSettingsSharp,
  BsBarChartLineFill,
  HiDocumentText,
  HiHome,
  FaFaceSmile,
  IoSendSharp,
  FaUserCircle,
  BiSolidPhoneCall,
  MdEmail,
  IoBriefcase,
  IoAddCircle,
  BsCheckCircleFill,
  HiOutlineVideoCamera,
  PiBellRingingFill,
  BsCalendar3,
  BsMessenger,
  IoBookmark,
  FiEdit,
  IoLogOutOutline,
  IoKeyOutline,
  IoBriefcaseOutline,
  BsFillImageFill,
  FaUserAlt,
  MdFontDownload,
  IoAlbumsSharp,
  AiOutlineBold,
  AiOutlineUnderline,
  AiOutlineItalic,
  FaCircleChevronUp,
  FaCircleChevronDown,
  FaCirclePlus,
  FaCircleXmark,
  FiSearch,
  FcGoogle,
  FiChevronDown,
};

export { icons };
